In [2]:
import pandas as pd
import numpy as np
data = pd.read_csv('/content/datamatdis_imupp.csv')
data

Nama        X1              X2                X3  \
0                Zaldi Abdul Hadi  Menengah  Proyek pribadi  30 menit - 1 jam   
1            Maulida Shifa Annisa    Pemula    Tugas Kuliah  30 menit - 1 jam   
2          Erlina Ayunda Cahyanti  Menengah    Tugas Kuliah           > 2 jam   
3        Aurelia Krisnanti Wijaya  Menengah    Tugas Kuliah           > 2 jam   
4             Dani Shofi Nur Izza    Pemula    Tugas Kuliah           > 2 jam   
..                            ...       ...             ...               ...   
104               Aquina Syabita   Menengah    Tugas Kuliah         1 - 2 jam   
105               Diah Anggraini   Menengah    Tugas Kuliah         1 - 2 jam   
106           Indy Dzakiyyatul M.    Pemula    Tugas Kuliah           > 2 jam   
107       Zelga Rahma Salsa Aziza    Pemula    Tugas Kuliah           > 2 jam   
108  Febriani Yolanda Tessalonika  Menengah    Tugas Kuliah           > 2 jam   

            X4  X5  X6  X7  X8  X9  X10  X11  X12  \
0    > 10 Kali   4   4   3   5   3    4    3    4   
1     ≤ 5 Kali   3   3   3   5   3    3    2    4   
2    > 10 Kali   5   4   1   5   4    4    4    4   
3    > 10 Kali   5   5   1   5   5    5    5    5   
4    > 10 Kali   5   5   3   5   4    2    3    5   
..         ...  ..  ..  ..  ..  ..  ...  ...  ...   
104   ≤ 5 Kali   3   3   3   3   3    3    3    3   
105  > 10 Kali   5   5   2   3   4    4    4    4   
106   ≤ 5 Kali   3   5   2   4   4    3    4    4   
107   ≤ 5 Kali   2   5   1   3   5    4    5    5   
108  > 10 Kali   4   4   4   4   3    4    3    4   

                                                   X13  \
0       Mengunggah data → Analisis data → Simpan hasil   
1       Menulis kode → Menjalankan program → Debugging   
2              Menulis kode → Error → Minta bantuan AI   
3              Menulis kode → Error → Minta bantuan AI   
4              Menulis kode → Error → Minta bantuan AI   
..                                                 ...   
104  Meminta syntax AI → Menulis kode → Menjalankan...   
105  Meminta syntax AI → Menulis kode → Menjalankan...   
106     Mengunggah data → Analisis data → Simpan hasil   
107  Meminta syntax AI → Menulis kode → Menjalankan...   
108     Mengunggah data → Analisis data → Simpan hasil   

                            X14  
0    Menulis / memperbaiki kode  
1    Menulis / memperbaiki kode  
2           Menjalankan program  
3    Menulis / memperbaiki kode  
4           Menjalankan program  
..                          ...  
104  Menulis / memperbaiki kode  
105         Menjalankan program  
106  Menulis / memperbaiki kode  
107         Menjalankan program  
108         Menjalankan program  

[109 rows x 15 columns]

In [4]:
data.dtypes


Nama    object
X1      object
X2      object
X3      object
X4      object
X5       int64
X6       int64
X7       int64
X8       int64
X9       int64
X10      int64
X11      int64
X12      int64
X13     object
X14     object
dtype: object

In [ ]:
cols = ['X1','X2','X3','X4']

# IDEA 1: Unweighted adjacency by exact match on at least one selected attribute
n = len(data)
adj1 = np.zeros((n, n), dtype=int)

for i in range(n):
    for j in range(n):
        if i != j:
            if any(data.loc[i, c] == data.loc[j, c] for c in cols):
                adj1[i, j] = 1

# IDEA 2: Weighted adjacency (similarity count)
adj2 = np.zeros((n, n), dtype=int)
for i in range(n):
    for j in range(n):
        if i != j:
            adj2[i, j] = sum(data.loc[i, c] == data.loc[j, c] for c in cols)

# IDEA 3: Matrix of hours categories (X3)
cats = data['X3'].unique()
cat_index = {c:i for i,c in enumerate(cats)}
k = len(cats)
mat3 = np.zeros((k, k), dtype=int)

# Count members in each category → diagonal matrix
for c in data['X3']:
    idx = cat_index[c]
    mat3[idx, idx] += 1

adj1[:5,:5], adj2[:5,:5], mat3

(array([[0, 1, 1, 1, 1],
        [1, 0, 1, 1, 1],
        [1, 1, 0, 1, 1],
        [1, 1, 1, 0, 1],
        [1, 1, 1, 1, 0]]),
 array([[0, 1, 2, 2, 1],
        [1, 0, 1, 1, 2],
        [2, 1, 0, 4, 3],
        [2, 1, 4, 0, 3],
        [1, 2, 3, 3, 0]]),
 array([[26,  0,  0,  0],
        [ 0, 41,  0,  0],
        [ 0,  0, 10,  0],
        [ 0,  0,  0, 32]]))